### ISSUE TITLE
Neo4j connection issue

### ISSUE THREAD

**Issue by yuanzhou** [x-atlas-consortia/ubkg-api#62]
I've noticed this issue several times, it happens after the neo4j instance is rebuilt or the ontology-api redeployed. A restart of the container may fix the issue but it comes back quickly.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ubkg_api/neo4j_manager.py", line 1020, in get_organ_types
    recds: neo4j.Result = session.run(query)
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_bolt4.py", line 334, in fetch_message
    details, summary_signature, summary_metadata = next(self.inbox)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_common.py", line 79, in __next__
    tag, fields = self.pop()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_common.py", line 73, in pop
    return next(self._messages)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/ubkg_api/routes/organs/organs_controller.py", line 11, in get_organ_types
    return jsonify(current_app.neo4jManager.get_organ_types(application_context.upper()))
  File "/usr/local/lib/python3.9/site-packages/ubkg_api/neo4j_manager.py", line 1026, in get_organ_types
    result.append(item)
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/simple.py", line 105, in __exit__
    self.close()
  File "/usr/local/lib/python3.9/site-packages/neo4j/work/simple.py", line 155, in close
    self._connection.fetch_all()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_bolt4.py", line 429, in fetch_all
    detail_delta, summary_delta = self.fetch_message()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_bolt4.py", line 334, in fetch_message
    details, summary_signature, summary_metadata = next(self.inbox)
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_common.py", line 79, in __next__
    tag, fields = self.pop()
  File "/usr/local/lib/python3.9/site-packages/neo4j/io/_common.py", line 73, in pop
    return next(self._messages)
StopIteration
```

As a result of this issue, the ingest-ui calls against the ontology-api would fail, and cause UI errors.
<img width="1339" alt="Screenshot 2023-07-13 at 9 58 24 PM" src="https://github.com/x-atlas-consortia/ubkg-api/assets/195873/6c117388-dcdc-4d54-a467-26e3ec49544b">

**Comment by yuanzhou** [comment]
Addressed by upgrading to neo4j python driver v4.4

**Comment by yuanzhou** [comment]
FYI @AlanSimmons Not sure if you keep tracking of this issue on the UBKG board, the fix has been merged as part of the refactoring work that @ChuckKollar worked on.

**Comment by AlanSimmons** [comment]
Thank you, @yuanzhou.

I'm waiting until the refactored UBKG API is in production before starting work on anything that depends on it being in place.
